version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/product_order_db"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: product_order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
